/*
 * M3ScaleAnalytics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using M3ScaleAnalytics.PCL.Controllers;
using M3ScaleAnalytics.PCL.Http.Client;

namespace M3ScaleAnalytics.PCL
{
    public partial class M3ScaleAnalyticsClient
    {

        /// <summary>
        /// Singleton access to ServiceOps controller
        /// </summary>
        public ServiceOpsController ServiceOps
        {
            get
            {
                return ServiceOpsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ApplicationOps controller
        /// </summary>
        public ApplicationOpsController ApplicationOps
        {
            get
            {
                return ApplicationOpsController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public M3ScaleAnalyticsClient() { }
    }
}