/*
 * M3ScaleAnalytics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using M3ScaleAnalytics.PCL;

namespace M3ScaleAnalytics.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum GranularityEnum
    {
        MONTH, //TODO: Write general description for this method
        DAY, //TODO: Write general description for this method
        HOUR, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type GranularityEnum
    /// </summary>
    public static class GranularityEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "month", "day", "hour" };

        /// <summary>
        /// Converts a GranularityEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The GranularityEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(GranularityEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case GranularityEnum.MONTH:
                case GranularityEnum.DAY:
                case GranularityEnum.HOUR:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of GranularityEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of GranularityEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<GranularityEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into GranularityEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed GranularityEnum value</returns>
        public static GranularityEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type GranularityEnum", value));

            return (GranularityEnum) index;
        }
    }
} 