/*
 * M3ScaleAnalytics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using M3ScaleAnalytics.PCL;

namespace M3ScaleAnalytics.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum TimezoneEnum
    {
        INTERNATIONAL_DATE_LINE_WEST, //TODO: Write general description for this method
        MIDWAY_ISLAND, //TODO: Write general description for this method
        AMERICAN_SAMOA, //TODO: Write general description for this method
        HAWAII, //TODO: Write general description for this method
        ALASKA, //TODO: Write general description for this method
        PACIFIC_TIME_US_CANADA, //TODO: Write general description for this method
        TIJUANA, //TODO: Write general description for this method
        MOUNTAIN_TIME_US_CANADA, //TODO: Write general description for this method
        ARIZONA, //TODO: Write general description for this method
        CHIHUAHUA, //TODO: Write general description for this method
        MAZATLAN, //TODO: Write general description for this method
        CENTRAL_TIME_US_CANADA, //TODO: Write general description for this method
        SASKATCHEWAN, //TODO: Write general description for this method
        GUADALAJARA, //TODO: Write general description for this method
        MEXICO_CITY, //TODO: Write general description for this method
        MONTERREY, //TODO: Write general description for this method
        CENTRAL_AMERICA, //TODO: Write general description for this method
        EASTERN_TIME_US_CANADA, //TODO: Write general description for this method
        INDIANA_EAST, //TODO: Write general description for this method
        BOGOTA, //TODO: Write general description for this method
        LIMA, //TODO: Write general description for this method
        QUITO, //TODO: Write general description for this method
        ATLANTIC_TIME_CANADA, //TODO: Write general description for this method
        CARACAS, //TODO: Write general description for this method
        LA_PAZ, //TODO: Write general description for this method
        SANTIAGO, //TODO: Write general description for this method
        NEWFOUNDLAND, //TODO: Write general description for this method
        BRASILIA, //TODO: Write general description for this method
        BUENOS_AIRES, //TODO: Write general description for this method
        GEORGETOWN, //TODO: Write general description for this method
        GREENLAND, //TODO: Write general description for this method
        MIDATLANTIC, //TODO: Write general description for this method
        AZORES, //TODO: Write general description for this method
        CAPE_VERDE_IS, //TODO: Write general description for this method
        DUBLIN, //TODO: Write general description for this method
        EDINBURGH, //TODO: Write general description for this method
        LISBON, //TODO: Write general description for this method
        LONDON, //TODO: Write general description for this method
        CASABLANCA, //TODO: Write general description for this method
        MONROVIA, //TODO: Write general description for this method
        UTC, //TODO: Write general description for this method
        BELGRADE, //TODO: Write general description for this method
        BRATISLAVA, //TODO: Write general description for this method
        BUDAPEST, //TODO: Write general description for this method
        LJUBLJANA, //TODO: Write general description for this method
        PRAGUE, //TODO: Write general description for this method
        SARAJEVO, //TODO: Write general description for this method
        SKOPJE, //TODO: Write general description for this method
        WARSAW, //TODO: Write general description for this method
        ZAGREB, //TODO: Write general description for this method
        BRUSSELS, //TODO: Write general description for this method
        COPENHAGEN, //TODO: Write general description for this method
        MADRID, //TODO: Write general description for this method
        PARIS, //TODO: Write general description for this method
        AMSTERDAM, //TODO: Write general description for this method
        BERLIN, //TODO: Write general description for this method
        BERN, //TODO: Write general description for this method
        ROME, //TODO: Write general description for this method
        STOCKHOLM, //TODO: Write general description for this method
        VIENNA, //TODO: Write general description for this method
        WEST_CENTRAL_AFRICA, //TODO: Write general description for this method
        BUCHAREST, //TODO: Write general description for this method
        CAIRO, //TODO: Write general description for this method
        HELSINKI, //TODO: Write general description for this method
        KYIV, //TODO: Write general description for this method
        RIGA, //TODO: Write general description for this method
        SOFIA, //TODO: Write general description for this method
        TALLINN, //TODO: Write general description for this method
        VILNIUS, //TODO: Write general description for this method
        ATHENS, //TODO: Write general description for this method
        ISTANBUL, //TODO: Write general description for this method
        MINSK, //TODO: Write general description for this method
        JERUSALEM, //TODO: Write general description for this method
        HARARE, //TODO: Write general description for this method
        PRETORIA, //TODO: Write general description for this method
        MOSCOW, //TODO: Write general description for this method
        ST_PETERSBURG, //TODO: Write general description for this method
        VOLGOGRAD, //TODO: Write general description for this method
        KUWAIT, //TODO: Write general description for this method
        RIYADH, //TODO: Write general description for this method
        NAIROBI, //TODO: Write general description for this method
        BAGHDAD, //TODO: Write general description for this method
        TEHRAN, //TODO: Write general description for this method
        ABU_DHABI, //TODO: Write general description for this method
        MUSCAT, //TODO: Write general description for this method
        BAKU, //TODO: Write general description for this method
        TBILISI, //TODO: Write general description for this method
        YEREVAN, //TODO: Write general description for this method
        KABUL, //TODO: Write general description for this method
        EKATERINBURG, //TODO: Write general description for this method
        ISLAMABAD, //TODO: Write general description for this method
        KARACHI, //TODO: Write general description for this method
        TASHKENT, //TODO: Write general description for this method
        CHENNAI, //TODO: Write general description for this method
        KOLKATA, //TODO: Write general description for this method
        MUMBAI, //TODO: Write general description for this method
        NEW_DELHI, //TODO: Write general description for this method
        KATHMANDU, //TODO: Write general description for this method
        ASTANA, //TODO: Write general description for this method
        DHAKA, //TODO: Write general description for this method
        SRI_JAYAWARDENEPURA, //TODO: Write general description for this method
        ALMATY, //TODO: Write general description for this method
        NOVOSIBIRSK, //TODO: Write general description for this method
        RANGOON, //TODO: Write general description for this method
        BANGKOK, //TODO: Write general description for this method
        HANOI, //TODO: Write general description for this method
        JAKARTA, //TODO: Write general description for this method
        KRASNOYARSK, //TODO: Write general description for this method
        BEIJING, //TODO: Write general description for this method
        CHONGQING, //TODO: Write general description for this method
        HONG_KONG, //TODO: Write general description for this method
        URUMQI, //TODO: Write general description for this method
        KUALA_LUMPUR, //TODO: Write general description for this method
        SINGAPORE, //TODO: Write general description for this method
        TAIPEI, //TODO: Write general description for this method
        PERTH, //TODO: Write general description for this method
        IRKUTSK, //TODO: Write general description for this method
        ULAAN_BATAAR, //TODO: Write general description for this method
        SEOUL, //TODO: Write general description for this method
        OSAKA, //TODO: Write general description for this method
        SAPPORO, //TODO: Write general description for this method
        TOKYO, //TODO: Write general description for this method
        YAKUTSK, //TODO: Write general description for this method
        DARWIN, //TODO: Write general description for this method
        ADELAIDE, //TODO: Write general description for this method
        CANBERRA, //TODO: Write general description for this method
        MELBOURNE, //TODO: Write general description for this method
        SYDNEY, //TODO: Write general description for this method
        BRISBANE, //TODO: Write general description for this method
        HOBART, //TODO: Write general description for this method
        VLADIVOSTOK, //TODO: Write general description for this method
        GUAM, //TODO: Write general description for this method
        PORT_MORESBY, //TODO: Write general description for this method
        MAGADAN, //TODO: Write general description for this method
        SOLOMON_IS, //TODO: Write general description for this method
        NEW_CALEDONIA, //TODO: Write general description for this method
        FIJI, //TODO: Write general description for this method
        KAMCHATKA, //TODO: Write general description for this method
        MARSHALL_IS, //TODO: Write general description for this method
        AUCKLAND, //TODO: Write general description for this method
        WELLINGTON, //TODO: Write general description for this method
        NUKUALOFA, //TODO: Write general description for this method
        TOKELAU_IS, //TODO: Write general description for this method
        SAMOA, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type TimezoneEnum
    /// </summary>
    public static class TimezoneEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "International Date Line West", "Midway Island", "American Samoa", "Hawaii", "Alaska", "Pacific Time (US & Canada)", "Tijuana", "Mountain Time (US & Canada)", "Arizona", "Chihuahua", "Mazatlan", "Central Time (US & Canada)", "Saskatchewan", "Guadalajara", "Mexico City", "Monterrey", "Central America", "Eastern Time (US & Canada)", "Indiana (East)", "Bogota", "Lima", "Quito", "Atlantic Time (Canada)", "Caracas", "La Paz", "Santiago", "Newfoundland", "Brasilia", "Buenos Aires", "Georgetown", "Greenland", "Mid-Atlantic", "Azores", "Cape Verde Is.", "Dublin", "Edinburgh", "Lisbon", "London", "Casablanca", "Monrovia", "UTC", "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague", "Sarajevo", "Skopje", "Warsaw", "Zagreb", "Brussels", "Copenhagen", "Madrid", "Paris", "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna", "West Central Africa", "Bucharest", "Cairo", "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius", "Athens", "Istanbul", "Minsk", "Jerusalem", "Harare", "Pretoria", "Moscow", "St. Petersburg", "Volgograd", "Kuwait", "Riyadh", "Nairobi", "Baghdad", "Tehran", "Abu Dhabi", "Muscat", "Baku", "Tbilisi", "Yerevan", "Kabul", "Ekaterinburg", "Islamabad", "Karachi", "Tashkent", "Chennai", "Kolkata", "Mumbai", "New Delhi", "Kathmandu", "Astana", "Dhaka", "Sri Jayawardenepura", "Almaty", "Novosibirsk", "Rangoon", "Bangkok", "Hanoi", "Jakarta", "Krasnoyarsk", "Beijing", "Chongqing", "Hong Kong", "Urumqi", "Kuala Lumpur", "Singapore", "Taipei", "Perth", "Irkutsk", "Ulaan Bataar", "Seoul", "Osaka", "Sapporo", "Tokyo", "Yakutsk", "Darwin", "Adelaide", "Canberra", "Melbourne", "Sydney", "Brisbane", "Hobart", "Vladivostok", "Guam", "Port Moresby", "Magadan", "Solomon Is.", "New Caledonia", "Fiji", "Kamchatka", "Marshall Is.", "Auckland", "Wellington", "Nuku'alofa", "Tokelau Is.", "Samoa" };

        /// <summary>
        /// Converts a TimezoneEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The TimezoneEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(TimezoneEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case TimezoneEnum.INTERNATIONAL_DATE_LINE_WEST:
                case TimezoneEnum.MIDWAY_ISLAND:
                case TimezoneEnum.AMERICAN_SAMOA:
                case TimezoneEnum.HAWAII:
                case TimezoneEnum.ALASKA:
                case TimezoneEnum.PACIFIC_TIME_US_CANADA:
                case TimezoneEnum.TIJUANA:
                case TimezoneEnum.MOUNTAIN_TIME_US_CANADA:
                case TimezoneEnum.ARIZONA:
                case TimezoneEnum.CHIHUAHUA:
                case TimezoneEnum.MAZATLAN:
                case TimezoneEnum.CENTRAL_TIME_US_CANADA:
                case TimezoneEnum.SASKATCHEWAN:
                case TimezoneEnum.GUADALAJARA:
                case TimezoneEnum.MEXICO_CITY:
                case TimezoneEnum.MONTERREY:
                case TimezoneEnum.CENTRAL_AMERICA:
                case TimezoneEnum.EASTERN_TIME_US_CANADA:
                case TimezoneEnum.INDIANA_EAST:
                case TimezoneEnum.BOGOTA:
                case TimezoneEnum.LIMA:
                case TimezoneEnum.QUITO:
                case TimezoneEnum.ATLANTIC_TIME_CANADA:
                case TimezoneEnum.CARACAS:
                case TimezoneEnum.LA_PAZ:
                case TimezoneEnum.SANTIAGO:
                case TimezoneEnum.NEWFOUNDLAND:
                case TimezoneEnum.BRASILIA:
                case TimezoneEnum.BUENOS_AIRES:
                case TimezoneEnum.GEORGETOWN:
                case TimezoneEnum.GREENLAND:
                case TimezoneEnum.MIDATLANTIC:
                case TimezoneEnum.AZORES:
                case TimezoneEnum.CAPE_VERDE_IS:
                case TimezoneEnum.DUBLIN:
                case TimezoneEnum.EDINBURGH:
                case TimezoneEnum.LISBON:
                case TimezoneEnum.LONDON:
                case TimezoneEnum.CASABLANCA:
                case TimezoneEnum.MONROVIA:
                case TimezoneEnum.UTC:
                case TimezoneEnum.BELGRADE:
                case TimezoneEnum.BRATISLAVA:
                case TimezoneEnum.BUDAPEST:
                case TimezoneEnum.LJUBLJANA:
                case TimezoneEnum.PRAGUE:
                case TimezoneEnum.SARAJEVO:
                case TimezoneEnum.SKOPJE:
                case TimezoneEnum.WARSAW:
                case TimezoneEnum.ZAGREB:
                case TimezoneEnum.BRUSSELS:
                case TimezoneEnum.COPENHAGEN:
                case TimezoneEnum.MADRID:
                case TimezoneEnum.PARIS:
                case TimezoneEnum.AMSTERDAM:
                case TimezoneEnum.BERLIN:
                case TimezoneEnum.BERN:
                case TimezoneEnum.ROME:
                case TimezoneEnum.STOCKHOLM:
                case TimezoneEnum.VIENNA:
                case TimezoneEnum.WEST_CENTRAL_AFRICA:
                case TimezoneEnum.BUCHAREST:
                case TimezoneEnum.CAIRO:
                case TimezoneEnum.HELSINKI:
                case TimezoneEnum.KYIV:
                case TimezoneEnum.RIGA:
                case TimezoneEnum.SOFIA:
                case TimezoneEnum.TALLINN:
                case TimezoneEnum.VILNIUS:
                case TimezoneEnum.ATHENS:
                case TimezoneEnum.ISTANBUL:
                case TimezoneEnum.MINSK:
                case TimezoneEnum.JERUSALEM:
                case TimezoneEnum.HARARE:
                case TimezoneEnum.PRETORIA:
                case TimezoneEnum.MOSCOW:
                case TimezoneEnum.ST_PETERSBURG:
                case TimezoneEnum.VOLGOGRAD:
                case TimezoneEnum.KUWAIT:
                case TimezoneEnum.RIYADH:
                case TimezoneEnum.NAIROBI:
                case TimezoneEnum.BAGHDAD:
                case TimezoneEnum.TEHRAN:
                case TimezoneEnum.ABU_DHABI:
                case TimezoneEnum.MUSCAT:
                case TimezoneEnum.BAKU:
                case TimezoneEnum.TBILISI:
                case TimezoneEnum.YEREVAN:
                case TimezoneEnum.KABUL:
                case TimezoneEnum.EKATERINBURG:
                case TimezoneEnum.ISLAMABAD:
                case TimezoneEnum.KARACHI:
                case TimezoneEnum.TASHKENT:
                case TimezoneEnum.CHENNAI:
                case TimezoneEnum.KOLKATA:
                case TimezoneEnum.MUMBAI:
                case TimezoneEnum.NEW_DELHI:
                case TimezoneEnum.KATHMANDU:
                case TimezoneEnum.ASTANA:
                case TimezoneEnum.DHAKA:
                case TimezoneEnum.SRI_JAYAWARDENEPURA:
                case TimezoneEnum.ALMATY:
                case TimezoneEnum.NOVOSIBIRSK:
                case TimezoneEnum.RANGOON:
                case TimezoneEnum.BANGKOK:
                case TimezoneEnum.HANOI:
                case TimezoneEnum.JAKARTA:
                case TimezoneEnum.KRASNOYARSK:
                case TimezoneEnum.BEIJING:
                case TimezoneEnum.CHONGQING:
                case TimezoneEnum.HONG_KONG:
                case TimezoneEnum.URUMQI:
                case TimezoneEnum.KUALA_LUMPUR:
                case TimezoneEnum.SINGAPORE:
                case TimezoneEnum.TAIPEI:
                case TimezoneEnum.PERTH:
                case TimezoneEnum.IRKUTSK:
                case TimezoneEnum.ULAAN_BATAAR:
                case TimezoneEnum.SEOUL:
                case TimezoneEnum.OSAKA:
                case TimezoneEnum.SAPPORO:
                case TimezoneEnum.TOKYO:
                case TimezoneEnum.YAKUTSK:
                case TimezoneEnum.DARWIN:
                case TimezoneEnum.ADELAIDE:
                case TimezoneEnum.CANBERRA:
                case TimezoneEnum.MELBOURNE:
                case TimezoneEnum.SYDNEY:
                case TimezoneEnum.BRISBANE:
                case TimezoneEnum.HOBART:
                case TimezoneEnum.VLADIVOSTOK:
                case TimezoneEnum.GUAM:
                case TimezoneEnum.PORT_MORESBY:
                case TimezoneEnum.MAGADAN:
                case TimezoneEnum.SOLOMON_IS:
                case TimezoneEnum.NEW_CALEDONIA:
                case TimezoneEnum.FIJI:
                case TimezoneEnum.KAMCHATKA:
                case TimezoneEnum.MARSHALL_IS:
                case TimezoneEnum.AUCKLAND:
                case TimezoneEnum.WELLINGTON:
                case TimezoneEnum.NUKUALOFA:
                case TimezoneEnum.TOKELAU_IS:
                case TimezoneEnum.SAMOA:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of TimezoneEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of TimezoneEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<TimezoneEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into TimezoneEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed TimezoneEnum value</returns>
        public static TimezoneEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type TimezoneEnum", value));

            return (TimezoneEnum) index;
        }
    }
} 